import 'dart:io';
import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:intl/intl.dart';
import 'package:image_picker/image_picker.dart';
import '../data/models/wallet_topup_model.dart';
import '../providers/wallet_provider.dart';

class WalletController extends GetxController {
  final WalletProvider _provider = Get.find<WalletProvider>();

  // Observable variables
  final RxList<WalletTopup> topupHistory = <WalletTopup>[].obs;
  final RxBool isLoading = false.obs;
  final RxBool isSubmitting = false.obs;
  final RxDouble walletBalance = 0.0.obs;

  // Form controllers
  final amountController = TextEditingController();
  final Rx<XFile?> selectedImage = Rx<XFile?>(null);

  // Unique code display
  final RxInt uniqueCode = 0.obs;
  final RxDouble transferAmount = 0.0.obs;
  final RxString qrString = ''.obs;
  final RxString qrisImageUrl = ''.obs;

  // Bank info
  final RxString bankName = ''.obs;
  final RxString accountNumber = ''.obs;
  final RxString accountName = ''.obs;

  final ImagePicker _picker = ImagePicker();

  @override
  void onInit() {
    super.onInit();
    fetchTopupHistory();
    fetchWalletBalance();
    fetchQrisCode();
  }

  @override
  void onClose() {
    amountController.dispose();
    super.onClose();
  }

  /// Pick image from gallery or camera
  Future<void> pickImage(ImageSource source) async {
    try {
      final XFile? image = await _picker.pickImage(
        source: source,
        maxWidth: 1920,
        maxHeight: 1080,
        imageQuality: 85,
      );

      if (image != null) {
        selectedImage.value = image;
        debugPrint('Image selected: ${image.path}');
      }
    } catch (e) {
      debugPrint('Error picking image: $e');
      Get.snackbar(
        'Error',
        'Gagal memilih gambar: ${e.toString()}',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    }
  }

  /// Clear selected image
  void clearImage() {
    selectedImage.value = null;
  }

  /// Calculate transfer amount preview (actual unique code comes from server)
  void calculateTransferAmount() {
    final amount = double.tryParse(amountController.text);
    if (amount != null && amount >= 10000) {
      // Preview only — actual unique code is generated by server (random 100-999)
      uniqueCode.value = 0;
      transferAmount.value = amount;
    } else {
      uniqueCode.value = 0;
      transferAmount.value = 0;
    }
  }

  /// Submit topup request
  Future<void> submitTopup() async {
    // Validate amount
    final amount = double.tryParse(amountController.text);
    if (amount == null || amount < 10000) {
      Get.snackbar(
        'Jumlah Tidak Valid',
        'Minimum topup adalah Rp 10.000',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.orange,
        colorText: Colors.white,
      );
      return;
    }

    // Validate image
    if (selectedImage.value == null) {
      Get.snackbar(
        'Upload Bukti',
        'Silakan upload bukti transfer',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.orange,
        colorText: Colors.white,
      );
      return;
    }

    isSubmitting.value = true;

    try {
      final response = await _provider.submitTopup(
        amount,
        File(selectedImage.value!.path),
      );

      if (response.statusCode == 200 || response.statusCode == 201) {
        final data = response.body as Map<String, dynamic>?;

        // Show verification confirmation dialog with server values
        if (data?['meta']?['status'] == 'success' && data?['data'] != null) {
          final serverData = data!['data'] as Map<String, dynamic>;
          _showTopupConfirmationDialog(serverData);
        } else {
          Get.snackbar(
            'Topup Berhasil',
            'Permintaan topup berhasil dibuat. Silakan tunggu verifikasi admin.',
            snackPosition: SnackPosition.BOTTOM,
            backgroundColor: Colors.green,
            colorText: Colors.white,
            duration: const Duration(seconds: 4),
          );
        }

        // Clear form
        amountController.clear();
        clearImage();
        uniqueCode.value = 0;
        transferAmount.value = 0;

        // Refresh history & balance
        fetchTopupHistory();
        fetchWalletBalance();
      } else {
        final data = response.body as Map<String, dynamic>?;
        final errorMessage = data?['message'] ?? 'Terjadi kesalahan';
        Get.snackbar(
          'Topup Gagal',
          errorMessage,
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red,
          colorText: Colors.white,
        );
      }
    } catch (e) {
      debugPrint('Error submitting topup: $e');
      Get.snackbar(
        'Error',
        'Gagal mengirim permintaan topup: ${e.toString()}',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    } finally {
      isSubmitting.value = false;
    }
  }

  /// Show confirmation dialog after successful topup submission
  void _showTopupConfirmationDialog(Map<String, dynamic> serverData) {
    final serverAmount = serverData['amount'] ?? 0;
    final serverUniqueCode = serverData['unique_code'] ?? 0;
    final serverTransferAmount = serverData['transfer_amount'] ?? 0;
    final status = serverData['status'] ?? 'PENDING';
    final instructions = serverData['instructions'] as List<dynamic>? ?? [];

    final formatter = NumberFormat.currency(
      locale: 'id_ID',
      symbol: 'Rp ',
      decimalDigits: 0,
    );

    Get.dialog(
      Dialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
        child: Container(
          padding: const EdgeInsets.all(24),
          child: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              // Success icon
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.green.shade50,
                  shape: BoxShape.circle,
                ),
                child: Icon(
                  Icons.check_circle,
                  size: 48,
                  color: Colors.green.shade600,
                ),
              ),
              const SizedBox(height: 16),

              // Title
              const Text(
                'Topup Berhasil Diajukan!',
                style: TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 8),
              Text(
                'Status: $status',
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.orange.shade700,
                  fontWeight: FontWeight.w600,
                ),
              ),
              const SizedBox(height: 16),

              // Transfer details card
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.blue.shade50,
                  borderRadius: BorderRadius.circular(12),
                  border: Border.all(color: Colors.blue.shade200),
                ),
                child: Column(
                  children: [
                    _detailRow('Nominal:', formatter.format(serverAmount)),
                    const Divider(height: 16),
                    _detailRow('Kode Unik:', '+$serverUniqueCode',
                        valueColor: Colors.blue.shade800),
                    const Divider(height: 16),
                    _detailRow('TOTAL Transfer:',
                        formatter.format(serverTransferAmount),
                        valueColor: Colors.green.shade700,
                        isBold: true,
                        fontSize: 18),
                  ],
                ),
              ),
              const SizedBox(height: 12),

              // Warning
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.orange.shade50,
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Colors.orange.shade300),
                ),
                child: Row(
                  children: [
                    Icon(Icons.warning_amber_rounded,
                        color: Colors.orange.shade700, size: 20),
                    const SizedBox(width: 8),
                    Expanded(
                      child: Text(
                        'Transfer HARUS tepat sesuai nominal di atas agar verifikasi berhasil!',
                        style: TextStyle(
                          fontSize: 12,
                          color: Colors.orange.shade800,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ),
                  ],
                ),
              ),

              // Instructions
              if (instructions.isNotEmpty) ...[
                const SizedBox(height: 12),
                ...instructions.map((i) => Padding(
                      padding: const EdgeInsets.symmetric(vertical: 2),
                      child: Row(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Text('• ',
                              style: TextStyle(
                                  fontSize: 12, color: Colors.grey.shade600)),
                          Expanded(
                            child: Text(
                              i.toString(),
                              style: TextStyle(
                                  fontSize: 12, color: Colors.grey.shade600),
                            ),
                          ),
                        ],
                      ),
                    )),
              ],

              const SizedBox(height: 20),

              // OK button
              SizedBox(
                width: double.infinity,
                child: ElevatedButton(
                  onPressed: () => Get.back(),
                  style: ElevatedButton.styleFrom(
                    backgroundColor: Colors.green,
                    foregroundColor: Colors.white,
                    padding: const EdgeInsets.symmetric(vertical: 14),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                  child: const Text('Mengerti',
                      style:
                          TextStyle(fontSize: 16, fontWeight: FontWeight.bold)),
                ),
              ),
            ],
          ),
        ),
      ),
      barrierDismissible: false,
    );
  }

  /// Helper for detail rows in the confirmation dialog
  Widget _detailRow(String label, String value,
      {Color? valueColor, bool isBold = false, double fontSize = 14}) {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(label,
            style: TextStyle(fontSize: 14, color: Colors.grey.shade700)),
        Text(
          value,
          style: TextStyle(
            fontSize: fontSize,
            fontWeight: isBold ? FontWeight.bold : FontWeight.w600,
            color: valueColor ?? Colors.black87,
          ),
        ),
      ],
    );
  }

  /// Fetch topup history
  Future<void> fetchTopupHistory() async {
    try {
      isLoading.value = true;
      debugPrint('[Wallet] Fetching topup history...');

      final response = await _provider.getTopupHistory();
      debugPrint('[Wallet] History response: status=${response.statusCode}');

      if (response.statusCode == 200) {
        final data = response.body;
        if (data != null &&
            data['meta']?['status'] == 'success' &&
            data['data'] != null) {
          final topupsData = data['data'];
          // Handle both paginated and non-paginated responses
          final List topupsList;
          if (topupsData is Map && topupsData.containsKey('topups')) {
            topupsList = topupsData['topups'] as List;
          } else if (topupsData is List) {
            topupsList = topupsData;
          } else {
            topupsList = [];
          }
          topupHistory.assignAll(
            topupsList.map((t) => WalletTopup.fromJson(t)).toList(),
          );
          debugPrint('[Wallet] Loaded ${topupHistory.length} topup records');
        }
      } else {
        debugPrint(
            '[Wallet] History error: ${response.statusCode} - ${response.statusText}');
      }
    } catch (e) {
      debugPrint('[Wallet] Error fetching topup history: $e');
    } finally {
      isLoading.value = false;
    }
  }

  /// Fetch wallet balance
  Future<void> fetchWalletBalance() async {
    try {
      debugPrint('[Wallet] Fetching wallet balance...');
      final response = await _provider.getWalletBalance();
      debugPrint('[Wallet] Balance response: status=${response.statusCode}');

      if (response.statusCode == 200) {
        final data = response.body;
        if (data != null &&
            data['meta']?['status'] == 'success' &&
            data['data'] != null) {
          walletBalance.value =
              double.tryParse(data['data']['balance'].toString()) ?? 0.0;
          debugPrint('[Wallet] Balance: ${walletBalance.value}');
        }
      } else {
        debugPrint(
            '[Wallet] Balance error: ${response.statusCode} - ${response.body}');
      }
    } catch (e) {
      debugPrint('[Wallet] Error fetching wallet balance: $e');
    }
  }

  /// Fetch QRIS code
  Future<void> fetchQrisCode() async {
    try {
      debugPrint('[Wallet] Fetching QRIS code...');
      final response = await _provider.getQrisCode();
      debugPrint(
          '[Wallet] QRIS response: status=${response.statusCode}, body=${response.body}');

      if (response.statusCode == 200) {
        final data = response.body;
        if (data != null &&
            data['meta']?['status'] == 'success' &&
            data['data'] != null) {
          qrisImageUrl.value = data['data']['qris_url'] ?? '';
          bankName.value = data['data']['bank_info']?['bank_name'] ?? '';
          accountNumber.value =
              data['data']['bank_info']?['account_number'] ?? '';
          accountName.value = data['data']['bank_info']?['account_name'] ?? '';
          debugPrint('[Wallet] QRIS URL set to: ${qrisImageUrl.value}');
          debugPrint(
              '[Wallet] Bank: ${bankName.value} - ${accountNumber.value}');
        } else {
          debugPrint('[Wallet] QRIS data is null or success=false');
        }
      } else {
        debugPrint(
            '[Wallet] QRIS error: ${response.statusCode} - ${response.statusText}');
      }
    } catch (e, stackTrace) {
      debugPrint('[Wallet] Error fetching QRIS code: $e');
      debugPrint('[Wallet] Stack: $stackTrace');
    }
  }

  /// Download QRIS code to device
  Future<void> downloadQrisCode() async {
    try {
      Get.snackbar(
        'Mengunduh...',
        'QRIS code sedang diunduh ke perangkat Anda',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.blue,
        colorText: Colors.white,
        duration: const Duration(seconds: 2),
      );

      final savedPath = await _provider.downloadQrisCode();

      if (savedPath != null) {
        Get.snackbar(
          'Download Berhasil ✅',
          'QRIS disimpan di: $savedPath',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.green,
          colorText: Colors.white,
          duration: const Duration(seconds: 4),
        );
      } else {
        Get.snackbar(
          'Download Gagal',
          'Gagal menyimpan QRIS code. Periksa izin penyimpanan.',
          snackPosition: SnackPosition.BOTTOM,
          backgroundColor: Colors.red,
          colorText: Colors.white,
        );
      }
    } catch (e) {
      debugPrint('Error downloading QRIS code: $e');
      Get.snackbar(
        'Error',
        'Gagal mengunduh QRIS Code: ${e.toString()}',
        snackPosition: SnackPosition.BOTTOM,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    }
  }

  /// Refresh data
  Future<void> refresh() async {
    await Future.wait([
      fetchTopupHistory(),
      fetchWalletBalance(),
    ]);
  }
}
